import os

AddOption('--debug-build', action='store_true', dest='debug_build',
	default=False)

env = Environment()

env.ParseConfig('pkg-config --cflags --libs gl glu glew assimp')
env.Append(
	CPPPATH=['.', 'libs'],
	LIBS=['glut', 'boost_filesystem', 'boost_system'],
	CCFLAGS=['-std=c++11'])

if GetOption('debug_build'):
	env.Append(CCFLAGS=['-g', '-O0', '-D_DEBUG'])
else:
	env['CXX'] = 'clang++'
	#env['ENV']['TERM'] = os.environ['TERM']

core_objs = env.Object(Glob('libs/core/*.cpp'))
render_objs = env.Object([Glob('libs/render/*.cpp'), Glob('libs/render/detail/*.cpp')])
common_objs = [env.Object(Glob('resource/*.cpp')), render_objs, core_objs]

env.Program(['test_orkmesh.cpp', common_objs])
env.Program(['test_assimp.cpp', common_objs])
