env = Environment()
env.Append(
	CPPPATH=['.', 'libs'],
	CPPFLAGS=['-std=c++11', '-Wall']
)
env['CXX'] = 'clang++'

logger_objs = env.Object(Glob('core/*.cpp'))

env.Program(['main.cpp', logger_objs])

#env.Program('buf.cpp')
