import os

AddOption('--debug-build', action='store_true', dest='debug_build',
	default=False)

env = Environment()

env.ParseConfig('pkg-config --cflags --libs gl glu glew')
env.Append(
	CPPPATH=['.', 'libs'],
	LIBS=['glut', 'pthread'],
	CCFLAGS=['-std=c++11'])

env['CXX'] = 'clang++'

if GetOption('debug_build'):
	env.Append(CCFLAGS=['-g', '-O0', '-D_DEBUG'])
else:	
	if 'TERM' in env['ENV']:
		env['ENV']['TERM'] = os.environ['TERM']

core_objs = env.Object(Glob('libs/core/*.cpp'))
render_objs = env.Object([
	Glob('render/*.cpp'),
	Glob('libs/render/*.cpp'), Glob('libs/render/detail/*.cpp')])

common_objs = [core_objs, render_objs]

# tests
env.Program(['test_meshbuff_arrays.cpp', common_objs])
env.Program(['test_meshbuff_elements.cpp', common_objs])
env.Program(['test_meshbuff_stride.cpp', common_objs])
env.Program(['test_mesh.cpp', common_objs])
