import os

AddOption('--debug-build', action='store_true', dest='debug_build',
	default=False)

env = Environment()

env.ParseConfig('pkg-config --cflags --libs gl glu glew sdl2')
env.Append(
	LIBS=['glut', 'boost_filesystem', 'boost_system'],
	CPPPATH=['../'],
	CCFLAGS=['-std=c++11'])

if GetOption('debug_build'):
	env.Append(CCFLAGS=['-g', '-O0', '-D_DEBUG'])
else:
	env['CXX'] = 'clang++'
	env['ENV']['TERM'] = os.environ['TERM']

current_objs = env.Object(Glob('../*.cpp'))

env.Program(['cubes.cpp', current_objs])

