import os

AddOption('--debug-build', action='store_true', dest='debug_build',
	default=False)

env = Environment()

env.ParseConfig('pkg-config --cflags --libs gl glu glew sdl2')
env.Append(
	CPPPATH=['.', 'otr', 'libs/otr'],
	LIBS=['glut', 'boost_filesystem', 'boost_system'],
	CCFLAGS=['-std=c++11'])

if GetOption('debug_build'):
	env.Append(CCFLAGS=['-g', '-O0', '-D_DEBUG'])
else:
	env['CXX'] = 'clang++'
	if 'TERM' in env['ENV']:
		env['ENV']['TERM'] = os.environ['TERM']

libs_objs = env.Object([
	Glob('libs/otr/render/*.cpp'), Glob('libs/otr/render/detail/*.cpp'),
	Glob('otr/render/*.cpp'), Glob('otr/render/detail/*.cpp'),
	Glob('libs/otr/ui/*.cpp')])

texture_objs = env.Object([
	Glob('render/*.cpp'), Glob('render/detail/*.cpp')])

common_objs = [libs_objs, texture_objs]

# tests
env.Program(['main.cpp', common_objs])

