env = Environment(
	#CXX=['clang++'],
	CXXFLAGS=['-std=c++11'],
	CCFLAGS=['-g', '-O0', '-Wall', '-Wno-ignored-attributes', '-Wno-sign-compare'],
	CPPPATH=['.', 'libs'],
	LIBS=['glut', 'pthread', 'jpeg'],
	CPPDEFINES=['GLM_FORCE_RADIANS'])

env.ParseConfig('pkg-config --cflags --libs glew Magick++ libpng12')

gl_objs = env.Object([Glob('libs/gl/*.cpp'), Glob('gl/*.cpp')])
gles2_objs = env.Object([Glob('libs/gl/gles2/*.cpp'), Glob('gl/gles2/*.cpp')])
pix_objs = env.Object([Glob('libs/pix/*.cpp')])

env.Program(['main.cpp', gl_objs, gles2_objs, pix_objs])
