import os

AddOption('--debug-build', action='store_true', dest='debug_build',
	default=False)

env = Environment()

env.ParseConfig('pkg-config --cflags --libs gl glu glew')
env.Append(
	CPPPATH=['.', 'libs'],
	LIBS=['glut', 'boost_filesystem', 'boost_system'],
	CCFLAGS=['-std=c++11'])

if GetOption('debug_build'):
	env.Append(CCFLAGS=['-g', '-O0', '-D_DEBUG'])
else:
	env['CXX'] = 'clang++'
	#env['ENV']['TERM'] = os.environ['TERM']

render_objs = env.Object(Glob('libs/render/*.cpp'))

common_objs = [env.Object(['resource/mesh_loader.cpp']), render_objs]

env.Program(['main.cpp', common_objs])
