env = Environment()

env.ParseConfig('pkg-config --cflags --libs gl glu glew')

env.Append(
	CCFLAGS = ['-std=c++11', '-g', '-O0'],
	LIBS = ['glut', 'boost_filesystem', 'boost_system', 'SOIL']
)

common_objs = env.Object(['src/program.cpp', 'texture.cpp'])

env.Program(['simple.cpp', common_objs])
env.Program(['scaled.cpp', common_objs])
env.Program(['test_strip_plane.cpp', 'src/plane.cpp', common_objs])
env.Program(['test_triangle_plane.cpp', 'src/triangle_plane.cpp', common_objs])
env.Program(['procedural.cpp', common_objs])
