env = Environment(
	CXX='clang++',
	CCFLAGS=['-std=c++11', '-Wall', '-Wno-ignored-attributes', '-Wno-sign-compare', '-Wno-unknown-attributes', '-g', '-O0'],
	CPPPATH=['.', 'libs', 'gl'],
	LIBS=['glut', 'pthread'],
	CPPDEFINES=['GLM_FORCE_RADIANS'])

env.ParseConfig('pkg-config --cflags --libs glew')

gl_objs = env.Object([Glob('libs/gl/*.cpp')])

env.Program(['main.cpp', 'touch_joystick.cpp', gl_objs])
