env = Environment(
	CXXFLAGS=['-std=c++11'],
	CCFLAGS=['-g', '-O0', '-Wall', '-Wno-unknown-attributes', '-Wno-sign-compare'],
	CPPPATH=['.', 'libs'],
	LIBS=['glut', 'pthread'],
	CPPDEFINES=['GLM_FORCE_RADIANS'])

env.ParseConfig('pkg-config --cflags --libs glew Magick++')

gl_objs = env.Object([Glob('libs/gl/*.cpp'), Glob('gl/*.cpp')])

env.Program(['main.cpp', gl_objs])
