env = Environment()
env.ParseConfig('pkg-config --cflags --libs gl glu glew Magick++ assimp')

env.Append(
	LIBS=['glut', 'anttweakbar'],
	CPPPATH=['.', 'anttweakbar/include'],
	CXXFLAGS=['-std=c++11', '-g', '-O0'])

lib_objs = env.Object([
	'program.cpp', 'mesh.cpp', 'camera.cpp', 'texture.cpp', 'window.cpp'])

env.Program(['blur.cpp', lib_objs])
env.Program(['edge.cpp', lib_objs])
env.Program(['test_texture.cpp', lib_objs])
env.Program(['test_offrender.cpp', lib_objs])
