env = Environment()

env.ParseConfig('pkg-config --cflags --libs gl glu glew')

env['LIBS'].extend([
	'glut',
	'boost_filesystem',
	'boost_system'])

env['CCFLAGS'].extend(['-std=c++11', '-g', '-O0'])

common_objs = env.Object(['program.cpp', 'cube.cpp', 'camera.cpp'])

env.Program(['main.cpp', common_objs])
