env = Environment(
	CXXFLAGS=['-std=c++11'], 
	CCFLAGS=['-Wall', '-O0', '-g', '-Wno-unknown-attributes', '-Wno-sign-compare'],
	CPPPATH=['.', 'libs', 'libs/gl'],
	LIBS=['glut', 'pthread', 'boost_system', 'boost_filesystem'],
	CPPDEFINES=['GLM_FORCE_RADIANS'])

env.ParseConfig('pkg-config --cflags --libs glew Magick++ assimp bullet freetype2 openal vorbisfile')

al_objs = env.Object([Glob('libs/al/*.cpp'), Glob('al/*.cpp')])
gl_objs = env.Object([Glob('libs/gl/*.cpp'), Glob('gl/*.cpp')])
phys_objs = env.Object([Glob('libs/physics/*.cpp'), Glob('physics/*.cpp')])

game_objs = env.Object([
	'level.cpp', 
	'player.cpp', 
	'door.cpp', 
	'medkit.cpp', 
	'medkit_world.cpp',
	'sound.cpp',
	'game.cpp',
	'enemy.cpp'])

all_objs = [al_objs, gl_objs, phys_objs, game_objs]


#env.Program(['test/test_bitmap.cpp', gl_objs])
#env.Program(['test/test_dmesh.cpp', gl_objs])
#env.Program(['test/test_state.cpp'])
env.Program(['w3dclone.cpp', all_objs])
