AddOption('--debug-build', action='store_true', dest='debug_build',
	default=False)

env = Environment()

env.ParseConfig('pkg-config --cflags --libs gl glu glew assimp lua5.2')
env.Append(
	CPPPATH=['.', 'otr', 'libs/otr', 'libs/anttweakbar/include'],
	CPPFLAGS=['-std=c++11'],
	LIBS=['glut', 'pthread', 'anttweakbar']
)

if GetOption('debug_build'):
	env.Append(CCFLAGS=['-g', '-O0'])
else:
	env['CXX'] = 'clang++'
	if 'ENV' in env and 'TERM' in env['ENV']:
		env['ENV']['TERM'] = os.environ['TERM']

core_objs = env.Object(Glob('libs/otr/core/*.cpp'))
render_objs = env.Object([Glob('libs/otr/render/*.cpp'), Glob('libs/otr/render/detail/*.cpp'), Glob('otr/render/*.cpp')])
resource_objs = env.Object(Glob('libs/otr/resource/*.cpp'))
ui_objs = env.Object([Glob('libs/otr/ui/*.cpp'), Glob('otr/ui/*.cpp')])
scenegraph_objs = env.Object([Glob('libs/otr/scenegraph/*.cpp'), Glob('otr/scenegraph/*.cpp')])
taskgraph_objs = env.Object([Glob('libs/otr/taskgraph/*.cpp'), Glob('otr/taskgraph/*.cpp')])

objs = env.Object(['luatools.cpp', 'error_message.cpp'])

common_objs = [core_objs, render_objs, resource_objs, ui_objs, scenegraph_objs, taskgraph_objs, objs]

#env.Program(['test_vm.cpp', objs])
#env.Program(['main.cpp', objs])
#env.Program(['adr.cpp', objs])

env.Program([
	'tweakbar_main.cpp',
	'tweakbar_resource.cpp',
	'tweakbar_handler.cpp',
	'tweakbar_manager.cpp',
	'draw_tweakbar_task.cpp',
	common_objs])
