env = Environment(CXX='clang++')

env.ParseConfig('pkg-config --cflags --libs glew Magick++')
env.Append(
	CXXFLAGS=['-std=c++11'],
	CCFLAGS=['-Wall', '-Wno-unknown-attributes', '-Wno-sign-compare'],
	CPPPATH=['.'],
	LIBS=['glut'],	
	CPPDEFINES=['GLM_FORCE_RADIANS'])

env.Append(CCFLAGS=['-g', '-O0'])

# draw modes
env.Program('test_triangle.cpp')
env.Program('test_triangle_minimal.cpp')
env.Program('lines.cpp')
env.Program('lines_in_scene.cpp')

# basics
env.Program('test_transform.cpp')
env.Program('test_transform_minimal.cpp')
env.Program('test_animation.cpp')
env.Program('uniform_array.cpp')
env.Program('simple_shading.cpp')
env.Program('test_buffer_copy_write.cpp')
#env.Program('simple_dynamic_shading.cpp')  # not working
env.Program('vao.cpp')

# textures
env.Program('texture_storage.cpp')
env.Program('texture_image.cpp')
env.Program('test_screenshot.cpp')
env.Program('test_screenshot_fbo.cpp')

# light
env.Program('test_lighting.cpp')
