import os

AddOption('--debug-build', action='store_true', dest='debug_build',
	default=False)

env = Environment()

env.ParseConfig('pkg-config --cflags --libs gl glu glew')
env.Append(
	CPPPATH=['.'],
	LIBS=['glut'],
	CCFLAGS=['-std=c++11'])

if GetOption('debug_build'):
	env['CXX'] = 'clang++'
	env.Append(CCFLAGS=['-g', '-O0', '-D_DEBUG'])
else:
	env['CXX'] = 'clang++'
	if 'ENV' in env['ENV'] and 'TERM' in env['ENV']:
		env['ENV']['TERM'] = os.environ['TERM']

env.Program('triangle.cpp')
env.Program('triangle_minimal.cpp')
env.Program('transform.cpp')
env.Program('transform_minimal.cpp')
env.Program('animation.cpp')
env.Program('lighting.cpp')
env.Program('screenshot.cpp')
