env = Environment(
	CPPFLAGS=['-std=c++11'],
	CCFLAGS=['-Wall', '-g', '-O0'],
	CPPPATH=['.', '#libs'],
	CPPDEFINES=['GLM_FORCE_RADIANS'],
	LIBS=['glut', 'jpeg', 'pthread'])

env.ParseConfig('pkg-config --cflags --libs glew libpng12')

# disable warnings
env.Append(
	CCFLAGS=['-Wno-ignored-attributes', '-Wno-sign-compare', '-Wno-unknown-attributes'])

gl_lib = SConscript('libs/gl/SConscript', exports='env')
pix_lib = SConscript('libs/pix/SConscript', exports='env')
gles2_lib = SConscript('gles2/SConscript', exports='env')
common_objs = [gles2_lib, gl_lib, pix_lib]

env.Program(['test/gles2_texture.cpp', common_objs])
env.Program(['test/gles2_texture_loader.cpp', common_objs])
env.Program(['test/model_bare.cpp', common_objs])
env.Program(['test/model_with_textures.cpp', common_objs])
env.Program(['test/animation_md5.cpp', common_objs])
