env = Environment()

proland_dir = '/data/proland/'
ork_cpppath = [proland_dir+p for p in ['ork', 'ork/libraries']]
ork_libpath = [proland_dir+'ork']

env.Append(
	CCFLAGS = ['-DORK_API=', '-DTIXML_USE_STL'],
	CPPPATH = ork_cpppath,
	LIBPATH = ork_libpath
)

common_libs = ['GL', 'GLU', 'glut', 'GLEW', 'X11', 'tiff', 'pthread']

env.Program(
	'test_mesh.cpp', LIBS = ['ork', common_libs]
)

