import os

AddOption('--debug-build', action='store_true', dest='debug_build', 
	default=False)

env = Environment()

env.ParseConfig('pkg-config --cflags --libs gl glu glew sdl2')
env.Append(
	CPPPATH=['.'],
	CXXFLAGS=['-std=c++11'])

if GetOption('debug_build'):
	env.Append(CCFLAGS=['-g', '-O0', '-DDEBUG'])
else:
	env['CXX'] = 'clang++'
	if 'TERM' in env['ENV']:
		env['ENV']['TERM'] = os.environ['TERM']

common_objs = env.Object(['ui/event_handler.cpp', 'ui/window.cpp'])

# glut
env.Append(LIBS=['glut'])
env.Program([
	'test_glut.cpp',
	'ui/glut_window.cpp',
	common_objs])

# sdl
env.Program([
	'test_sdl.cpp',
	'ui/sdl_window.cpp',
	common_objs])

# sfml
#env.Program([
#	'test_sfml.cpp',
#	'sfml_window.cpp',
#	common_objs])
