import os

AddOption('--debug-build', action='store_true', dest='debug_build', 
	default=False)

env = Environment()

env.ParseConfig('pkg-config --cflags --libs gl glu glew sdl2')
env.Append(
	CPPPATH=['.'],
	CXXFLAGS=['-std=c++11'])

if GetOption('debug_build'):
	env.Append(CCFLAGS=['-g', '-O0', '-DDEBUG'])
else:
	env['CXX'] = 'clang++'
	if 'TERM' in env['ENV']:
		env['ENV']['TERM'] = os.environ['TERM']

core_objs = env.Object(Glob('core/*.cpp'))
ui_objs = env.Object(Glob('ui/*.cpp'))
common_objs = [ui_objs, core_objs]

# glut
env.Append(LIBS=['glut'])
env.Program(['test_glut.cpp',	common_objs])

# sdl
env.Program(['test_sdl.cpp', common_objs])
