import os

AddOption('--debug-build', action='store_true', dest='debug_build',
	default=False)

env = Environment()

env.ParseConfig('pkg-config --cflags --libs glew Magick++ assimp freetype2')

env.Append(
	CXXFLAGS=['-std=c++11'],
	CCFLAGS=['-Wall', '-Wno-unknown-attributes', '-Wno-sign-compare'],
	CPPPATH=['.'],
	LIBS=['glut', 'pthread'],	
	CPPDEFINES=['GLM_FORCE_RADIANS'])

if GetOption('debug_build'):
	env.Append(CCFLAGS=['-g', '-O0', '-D_DEBUG'])
else:
	env['CXX'] = 'clang++'
	if 'ENV' in env and 'TERM' in env['ENV']:
		env['ENV']['TERM'] = os.environ['TERM']

common_objs = env.Object([
	'camera.cpp',
	'texture.cpp',
	'mesh.cpp',
	'program.cpp',
	'window.cpp',
	'dtools.cpp',
	'label.cpp',
	'frustum.cpp',
	'image.cpp'])

env.Program(['test/test_parallaxdisp.cpp', common_objs])
env.Program(['test/test_normalmap.cpp', common_objs])
env.Program(['test/test_phong.cpp', common_objs])
env.Program(['test/test_parallaxnorm.cpp', common_objs])
env.Program(['test/test_texrender.cpp', common_objs])
env.Program(['test/test_offrender.cpp', common_objs])
env.Program(['test/test_texture.cpp', common_objs])
env.Program(['test/test_texture_create.cpp', common_objs])
env.Program(['test/test_texture_raw.cpp', common_objs])
env.Program(['test/test_blur.cpp', common_objs])
env.Program(['test/test_window.cpp', common_objs])
env.Program(['test/test_scene.cpp', common_objs])
env.Program(['test/test_texture_array.cpp', common_objs])
env.Program(['test/test_geometry.cpp', common_objs])
env.Program(['test/test_font.cpp', common_objs])
env.Program(['test/test_frustum.cpp', common_objs])
env.Program(['test/test_mesh.cpp', common_objs])
env.Program(['test/test_mesh_plane_xy.cpp', common_objs])
env.Program(['test/test_image.cpp', common_objs])
env.Program(['test/dynamic_shading.cpp', common_objs])

# program
env.Program(['test/uniform_array.cpp', common_objs])
