import os

AddOption('--debug-build', action='store_true', dest='debug_build',
	default=False)

env = Environment()

env.ParseConfig('pkg-config --cflags --libs gl glu glew sdl2')
env.Append(
	CPPPATH=['.', 'libs'],
	LIBS=['glut', 'boost_filesystem', 'boost_system'],
	CCFLAGS=['-std=c++11'])

if GetOption('debug_build'):
	env.Append(CCFLAGS=['-g', '-O0', '-D_DEBUG'])
else:
	env['CXX'] = 'clang++'
	#env['ENV']['TERM'] = os.environ['TERM']

scenegraph_objs = env.Object(Glob('scenegraph/*.cpp'))
taskgraph_objs = env.Object(Glob('taskgraph/*.cpp'))

common_objs = [
	env.Object(Glob('libs/render/*.cpp')),
	env.Object(Glob('libs/ui/*.cpp')),
	scenegraph_objs, taskgraph_objs]


env.Program(['main.cpp', common_objs])

