import os

AddOption('--debug-build', action='store_true', dest='debug_build',
	default=False)

env = Environment()

env.ParseConfig('pkg-config --cflags --libs gl glu glew')
env.Append(
	LIBS=['glut', 'boost_filesystem', 'boost_system'],
	CCFLAGS=['-std=c++11'])

if GetOption('debug_build'):
	env.Append(CCFLAGS=['-g', '-O0', '-D_DEBUG'])
else:
	env['CXX'] = 'clang++'
	env['ENV']['TERM'] = os.environ['TERM']


common_objs = env.Object([
	'buffer.cpp', 
	'framebuffer.cpp',
	'meshbuffers.cpp',
	'program.cpp']);


# tests
env.Program(['test_arrays.cpp', common_objs])
env.Program(['test_buffer.cpp', common_objs])
env.Program(['test_stride.cpp', common_objs])
env.Program(['test_elements.cpp', common_objs])

